apiVersion: apps/v1
kind: Deployment
metadata:
  name: javapplication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: javaapp
        image: himamshu5904/ciproject2:2025-07-21_2002
        ports:
        - containerPort: 8080
