apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  type: LoadBalancer     
  selector:
    app: java            
  ports:
    - protocol: TCP
      port: 80           
      targetPort: 8080
